/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MapContain: typeof import('./components/map/MapContain.vue')['default']
    Menu: typeof import('./components/navMenu/Menu.vue')['default']
    MenuItem: typeof import('./components/navMenu/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepForm: typeof import('./components/stepForm/StepForm.vue')['default']
    TopHeader: typeof import('./components/topHeader/TopHeader.vue')['default']
  }
}
